Calculos de comprobación.

In [7]:
import numpy as np

In [72]:
# Condiciones iniciales

Rt = 6.37816E6
Dtl = 3.844E8
# r
r = Rt/Dtl

# Phi
phi = -np.pi/3
theta = np.pi/3

v = 28000*10/36
v = v/Dtl

#  P_r
pr = v*0.5

# P_phi
pphi = r*v*np.sin(theta-phi)

print(f"Condiciones iniciales: r ={r}\n phi = {phi}\n p_r={pr}\n p_phi={pphi}")

Condiciones iniciales: r =0.016592507804370448
 phi = -1.0471975511965976
 p_r=1.0116776505954445e-05
 p_phi=2.9074671319671225e-07


In [48]:
t = 0
h = 60

In [49]:
def rdot(r,phi,pr,pphi,t):
	return pr

In [73]:
def phidot(r,phi,pr,pphi, t):
	return (pphi/r**2)

60*phidot(r, phi, pr, pphi,t)

0.06336391505273277

In [77]:
def prdot(r,phi,pr,pphi, t):
	G = 6.67E-11
	Mt = 5.9736E24
	Ml = 0.07349E24
	Delta = G*Mt/Dtl
	mu = Ml/Mt
	w = 2.6617E-6
	rtil = np.sqrt(1+r**2-2*r*np.cos(phi-w*t))
	return pphi**2 / r**3 - Delta*(1/r**2 + mu/rtil**3 * (r-np.cos(phi-w*t)))

In [47]:
def pphidot(r,phi,pr,pphi, t):
	G = 6.67E-11
	Mt = 5.9736E24
	Ml = 0.07349E24
	Delta = G*Mt/Dtl
	mu = Ml/Mt
	w = 2.6617E-6
	rtil = np.sqrt(1+r**2-2*r*np.cos(phi-w*t))
	return - Delta*mu*r*np.sin(phi-w*t)/rtil**3

In [65]:
K1 = np.zeros(4)
K1[0] = h* rdot(r,phi,pr,pphi,t)
K1[1] = h* phidot(r,phi,pr,pphi,t)
K1[2] = h* prdot(r,phi,pr,pphi,t)
K1[3] = h* pphidot(r,phi,pr,pphi,t)
print(K1)

[ 6.07006590e-04  6.33639151e-02 -2.25894186e+11  1.12689122e+04]


In [66]:
K2 = np.zeros(4)
K2[0] = h* rdot(r+0.5*K1[0],phi+0.5*K1[1],pr+0.5*K1[2],pphi+0.5*K1[3],t+0.5*h)
K2[1] = h* phidot(r+0.5*K1[0],phi+0.5*K1[1],pr+0.5*K1[2],pphi+0.5*K1[3],t+0.5*h)
K2[2] = h* prdot(r+0.5*K1[0],phi+0.5*K1[1],pr+0.5*K1[2],pphi+0.5*K1[3],t+0.5*h)
K2[3] = h* pphidot(r+0.5*K1[0],phi+0.5*K1[1],pr+0.5*K1[2],pphi+0.5*K1[3],t+0.5*h)
print(K2)

[-6.77682558e+12  1.18422678e+09  3.94696296e+14  1.12807767e+04]


In [67]:
K3 = np.zeros(4)
K3[0] = h* rdot(r+0.5*K2[0],phi+0.5*K2[1],pr+0.5*K2[2],pphi+0.5*K2[3],t+0.5*h)
K3[1] = h* phidot(r+0.5*K2[0],phi+0.5*K2[1],pr+0.5*K2[2],pphi+0.5*K2[3],t+0.5*h)
K3[2] = h* prdot(r+0.5*K2[0],phi+0.5*K2[1],pr+0.5*K2[2],pphi+0.5*K2[3],t+0.5*h)
K3[3] = h* pphidot(r+0.5*K2[0],phi+0.5*K2[1],pr+0.5*K2[2],pphi+0.5*K2[3],t+0.5*h)
print(K3)

[ 1.18408889e+16  2.94759379e-20 -5.35009124e-18 -5.34845864e-20]


In [68]:
K4 = np.zeros(4)
K4[0] = h* rdot(r+K3[0],phi+K3[1],pr+K3[2],pphi+K3[3],t+h)
K4[1] = h* phidot(r+K3[0],phi+K3[1],pr+K3[2],pphi+K3[3],t+h)
K4[2] = h* prdot(r+K3[0],phi+K3[1],pr+K3[2],pphi+K3[3],t+h)
K4[3] = h* pphidot(r+K3[0],phi+K3[1],pr+K3[2],pphi+K3[3],t+h)
print(K4)

[ 6.07006590e-04  1.24422079e-37 -4.49026038e-25  4.72632964e-27]


In [63]:
r = r + (K1[0]+2*K2[0]+2*K3[0]+K4[0])/6
r

3944704022859739.5